# Generated by Django 4.2.4 on 2024-07-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_no', models.CharField(max_length=20)),
                ('home_address', models.CharField(max_length=255)),
                ('school_year', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('civil_status', models.CharField(max_length=20)),
                ('blood_type', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=255)),
                ('parent_name', models.CharField(max_length=255)),
                ('landline', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=20)),
                ('has_medical_illness', models.CharField(max_length=255)),
                ('diseases', models.CharField(max_length=255)),
                ('food', models.CharField(max_length=255)),
                ('no_known_allergies', models.CharField(max_length=255)),
                ('medicines', models.CharField(max_length=255)),
                ('cigarette', models.CharField(max_length=255)),
                ('alcohol', models.CharField(max_length=255)),
            ],
        ),
    ]
